version: '3.8'

services:

  mongodb:
    image: mongo:6
    container_name: mongodb
    ports:
      - "27017:27017"

  express-class:
    build: .
    container_name: express-class
    environment:
      - .env
    depends_on:
      - mongodb
    ports:
      - "3000:3000"