name: Deploy Express App to EC2

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm ci


      - name: Remove old app.zip
        run: rm -rf app.zip

      - name: Archive project
        run: zip -r app.zip . -x "*.git*" "node_modules/*" ".github/*"

      - name: Code archive to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          source: "app.zip"
          target: "~"

      - name: Deploy on EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            set -e
            cd ~
            rm -rf express-test/
            sudo apt install -y unzip
            unzip -o app.zip -d express-test
            cd express-test
            cat <<EOF> .env
            JWT_SECRET_KEY= '${{ secrets.JWT_SECRET_KEY }}'
            GOOGLE_APP_PASSWORD= '${{ secrets.GOOGLE_APP_PASSWORD }}'
            GOOGLE_CLIENT_ID= '${{ secrets.GOOGLE_CLIENT_ID }}'
            GOOGLE_SECRET= '${{ secrets.GOOGLE_SECRET }}'
            AWS_ACCESS_KEY_ID= '${{ secrets.AWS_ACCESS_KEY_ID }}'
            AWS_SECRET_ACCESS_KEY= '${{ secrets.AWS_SECRET_ACCESS_KEY }}'
            AWS_BUCKET_NAME= '${{ secrets.AWS_BUCKET_NAME }}'
            AWS_REGION= '${{ secrets.AWS_REGION }}'
            EOF
            
            sudo apt install -y nodejs npm
            sudo npm ci
            sudo npm i -g pm2
            pm2 delete all || true
            pm2 start index.js --name express-test  